### ISSUE TITLE
'Unable to resolve type SvgImage from namespace'

### ISSUE THREAD

**Issue by g2asell2019** [TheAnachronism/ImageDataSetTagEditor#4]
When opened MainWindows.axaml, I got this error from output

`System.Xaml.XamlException: 'Unable to resolve type SvgImage from namespace https://github.com/avaloniaui Line 124, position 60.' Line number '124' and line position '60'.`

IDE extension list:
![image](https://github.com/TheAnachronism/ImageDataSetTagEditor/assets/51025883/b24bf58b-ffef-4e17-9796-62e6114a80f6)

**Comment by g2asell2019** [comment]
Problem is I already installed Svg packages for Avalonia and restart VS still got error with resolve type
![image](https://github.com/TheAnachronism/ImageDataSetTagEditor/assets/51025883/1ebc7fd6-5e9f-4c6b-ad51-01dbf65cf2dd)

**Comment by TheAnachronism** [comment]
Mhh, sorry but I've never encountered this.
I'm using Rider for my dotnet solutions and it doesn't have this problem.

Maybe Visual Studio needs more for Avalonia development?

EDIT:
Never mind, upgrading all nuget packages resultet in the same erros.
I'll see what I can do.

**Comment by TheAnachronism** [comment]
Alright, turns out, there were some bigger changes for Avalonia UI version 11.
I've fixed everything, and it should work with my most recent push to master.
